//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhinoDek2 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class MainSettingsFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainSettingsFile defaultInstance = ((MainSettingsFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainSettingsFile())));
        
        public static MainSettingsFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Windows8\"")]
        public string Store_Theme_Name {
            get {
                return ((string)(this["Store_Theme_Name"]));
            }
            set {
                this["Store_Theme_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Background {
            get {
                return ((string)(this["Background"]));
            }
            set {
                this["Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Null")]
        public string CAD_Drive {
            get {
                return ((string)(this["CAD_Drive"]));
            }
            set {
                this["CAD_Drive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Null")]
        public string Public_Drive {
            get {
                return ((string)(this["Public_Drive"]));
            }
            set {
                this["Public_Drive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Null")]
        public string CNC_Drive {
            get {
                return ((string)(this["CNC_Drive"]));
            }
            set {
                this["CNC_Drive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Title_Font_Color {
            get {
                return ((global::System.Drawing.Color)(this["Title_Font_Color"]));
            }
            set {
                this["Title_Font_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 12pt")]
        public global::System.Drawing.Font Tile_Font_Family {
            get {
                return ((global::System.Drawing.Font)(this["Tile_Font_Family"]));
            }
            set {
                this["Tile_Font_Family"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Background_Color {
            get {
                return ((global::System.Drawing.Color)(this["Background_Color"]));
            }
            set {
                this["Background_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PaperPrinterName {
            get {
                return ((string)(this["PaperPrinterName"]));
            }
            set {
                this["PaperPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PDFPrinterName {
            get {
                return ((string)(this["PDFPrinterName"]));
            }
            set {
                this["PDFPrinterName"] = value;
            }
        }
    }
}
